### ISSUE TITLE
Uses wrong index for sources.

### ISSUE THREAD

**Issue by gkwaerp** [madsroskar/IdeaGenerator#1]
https://github.com/madsroskar/IdeaGenerator/blob/6b0bff2d976170e55ab036a68f9650873cf41ad3/idea.go#L40

Should be s[source]

**Comment by madsroskar** [comment]
This is already fixed locally, I'll push it.

**Comment by madsroskar** [comment]
Fixed in f116689f65a83cdc34fb0b7e7af5508b7cec9886
